---
- name: Install rails dependencies
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages[ansible_os_family|lower] }}"
  become: true

- name: Check current node version
  shell: node --version 2>&1
  register: installed_node_version
  failed_when: false  # noqa 301
  changed_when: false

- name: Remove old nodejs versions and configs
  block:
    - name: remove old versions of node
      package:
        name: nodejs
        state: absent

    - name: get a list nodesource repo configs
      find:
        paths: /etc/yum.repos.d/
        patterns: "nodesource*.repo"
      register: nodesource_yum_repos
      when: ansible_facts['os_family'] == "RedHat"

    - name: remove old nodesource repo configs
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ nodesource_yum_repos.files }}"
      when: ansible_facts['os_family'] == "RedHat"

    - name: clean the cache so old repo config get fully removed
      command: yum clean all
      args:
        warn: false
  when: installed_node_version.stdout is not regex("v{{ nodejs_major_version }}.*") and
    ansible_facts['os_family'] == "RedHat"

- name: Import Nodesource RPM key (RH)
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Import Nodesource RPM key (Debian)
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Nodesource repositories for Node.js
  yum_repository:
    name: nodesource
    description: "nodesource package of nodejs for $basearch"
    baseurl: "https://rpm.nodesource.com/pub_{{ nodejs_major_version }}.x/el/{{ ansible_distribution_major_version }}/$basearch"  # noqa 204
    gpgcheck: true
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Nodesource repositories for Node.js
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_major_version }}.x {{ ansible_distribution_release }} main"  # noqa 204
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure Node.js and npm are installed.
  yum:
    name: "nodejs-{{ nodejs_version }}"
    state: present
    enablerepo: "nodesource"
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure Node.js and npm are installed.
  yum:
    name: "nodejs"
  when: ansible_facts['os_family'] == "Debian"


- name: Install yarn node package if this project needs it
  npm:
    name: yarn
    global: true
    state: present
    version: "{{ yarn_version }}"
  when: rails_app_use_webpack is defined and rails_app_use_webpack

- name: Install app specifc dependencies
  package:
    name: "{{ rails_app_additional_dependencies | default([]) }}"
    state: present
  become: true
