---

- name: Install rails dependencies
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - git-core
    - zlib
    - zlib-devel
    - gcc-c++
    - patch
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - curl
    - sqlite-devel
    - mariadb-devel
    - mariadb
    - epel-release
  become: yes

- name: install nodejs for asset pipeline for rails
  yum:
    name: nodejs
    state: present
  become: yes

- name: Install yarn node package if this project needs it
  npm:
    name: yarn
    global: yes
    state: present
  when: rails_app_use_webpack is defined and rails_app_use_webpack

- name: Install app specifc dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ rails_app_additional_dependencies }}"
  become: yes
