---

- name: make sure the firewalld service is started
  service:
    name: firewalld
    state: started
    enabled: yes
  become: yes
- name: Allow access to http traffic from the proxy
  firewalld:
    zone: internal
    state: enabled
    permanent: yes
    service: "{{ item.0 }}"
    source: "{{ item.1 | default(omit) }}"
    source: "{{ hostvars[groups.proxy[0]][(network_interface|default('ansible_eth0'))]['ipv4']['address'] }}"
  with_together: 
  - "{{ rails_app_firewall_services| default(['http','https']) }}"
  - "{{ rails_app_firewall_sources| default([None,None]) }}"
  notify: reload firewall
