---
# tasks file for rails_app


- include: dependencies.yml
- include: passenger-config.yml
- include: install-app.yml
- include: solr-config.yml
  when: is_local_blacklight_app
- include: environment.yml
- include: firewall.yml
  when: rails_app_use_firewall| default(false)

