---

- name: deploy yarn
  shell: >
    bash -lc 'RAILS_ENV={{ rails_app_env }} NODE_ENV=production {{ item }}'
  args:
    chdir: "{{ rails_app_install_path }}"  # noqa 305
  with_items:
    - "yarn install --frozen-lockfile --prod"
  become: true
  become_user: "{{ rails_app_user }}"
  when: rails_app_use_webpack is defined and rails_app_use_webpack
  notify: deploy tasks
  tags:
    - app

- name: deploy tasks
  command: >
    bash -lc 'RAILS_ENV={{ rails_app_env }} bundle exec rails {{ item }}'
  args:
    chdir: "{{ rails_app_install_path }}"
  with_items:
    - assets:clean
    - assets:precompile
  become: true
  become_user: "{{ rails_app_user }}"
  when: is_webserver
  notify:
    - restart passenger app
    - migrate db
  tags:
    - rails_app

- name: migrate db
  command: >
    bash -lc 'RAILS_ENV={{ rails_app_env }} bundle exec rails {{ item }}'
  args:
    chdir: "{{ rails_app_install_path }}"
  with_items:
    - db:migrate
  become: true
  become_user: "{{ rails_app_user }}"
  run_once: true
  when: is_webserver
  notify: restart passenger app
  tags:
    - rails_app

- name: restart passenger app
  command: >
    bash -lc 'passenger-config restart-app `pwd`'
  args:
    chdir: "{{ rails_app_install_path }}"
  become: true
  become_user: "{{ rails_app_user }}"
  when: is_webserver
  failed_when: false
  tags:
    - rails-app

- name: restart apache
  service:
    name: httpd
    state: restarted
  become: true
  when: is_webserver
  tags:
    - rails_app

- name: restart solr
  service:
    name: solr
    state: restarted
  become: true
  when: is_blacklight_app
  tags:
    - rails_app
